describe('This is my first Cypress Test', () => {
    it('Navigate to CCHQ', () => {
        cy.visit('https://staging.commcarehq.org/accounts/login/')
    })
    it('Log in to CCHQ', () => {
        cy.get('.navbar-brand > div').click()
        cy.get('#hs-eu-confirmation-button').click()
        cy.get('#id_auth-username').type("automation.user.commcarehq@gmail.com")
        cy.get('.form-bubble-actions > [type="button"]').click()
        cy.get('#id_auth-password').type("pass@123")
        cy.get('.form-bubble-actions > [type="submit"]').click()   
        cy.get('#CloudcareTab > a').click()
        cy.get('.js-restore-as-item').click()
        cy.get('[aria-label="test"] > .module-column-name').click()
        cy.get('#js-confirmation-confirm').click()
        cy.get('.js-application-container > .grid-item > .appicon').click() 
        cy.get('.module-column-name').click()
        cy.get('[aria-label="Registration Form"] > .module-column-name').click()
        cy.xpath('//span[text()="Woman\'s Name English"]/following::div[1]/div[@class="widget"]/descendant::textarea').type("Woman1")
        cy.xpath('//span[text()="Village Name"]/following::div[1]/div[@class="widget"]/descendant::textarea').type("Village Name1")
        cy.xpath('//span[text()="Date of Last Menstrual Period"]/following::div[1]/div[@class="widget"]/descendant::input').type("06/10/2021")
        cy.xpath('//span[text()="Date of Last Menstrual Period"]/following::div[1]/div[@class="widget"]/descendant::input').click()
        cy.xpath('//span[text()="Has the woman given birth to children that are still alive?"]/following::div[1]/div[@class="widget"]/descendant::input[@value="1"]').click()
        cy.get('.submit').click()
        cy.get('#cloudcare-notifications > .alert > p').should('have.text', 'Form successfully saved!')
     })
})