""""Contains test data that are used as user inputs across various areass used in Multi Select"""


class MultiSelectUserInput:
    """User Test Data"""

    """App Names"""
    multiselect_app_name = "Multi-Select"

    """Menu Names"""
    shadow_auto = "Shadow Menu (Auto-Proceed)"
    display_only_forms_auto = "Display Only Forms plus Multi-Case Form"
    songs_manual = "Songs (multi select, normal, manual w/max limit)"
    songs_auto_max_limit = " Songs (multi select, normal,  auto, selected cases > max limit)"
    songs_auto = "Songs (multi select, normal, auto w/max limit)"
    songs_multi_normal = "Songs (multi select, normal, non-inline search)"
    songs_multi_search_first = "Songs (multi select, search-first, inline search)"
    songs_multi_skip_es = "Songs (multi select, skip-es, inline search)"
    songs_multi_see_more = "Songs (multi select, see-more, inline search)"
    songs_MS_SF_IS = "Songs (multi select, search-first, inline search)"
    songs_MS_N_NIS = "Songs (multi select, normal, non-inline search)"
    songs_Non_Multi = "Songs (non-multi, no inline search)"
    shows_MS_SPFP = "Shows (multi, select-first: parent)"
    shows_MS_SPFO = "Shows (multi, select-first: other)"
    yet_another_show_NMS = "Yet Another Shows (non-multi)"
    another_shows_non = "Another Shows (non)"
    child_shows_SF_MS = "Child Shows + Search First(multi)"
    child_shows_N_MS = "Child Shows + Normal (multi)"
    another_shows_MS = "Another Show (multi)"
    another_shows_not_MS = "Another Show (non-multi)"
    shadow_menu_multi = "Shadow Menu"
    shadow_senu_non_multi = "Shadow Menu (Non-Multi)"
    display_only_forms = "Display Only Forms plus Multi-Case Form"

    """Form Names"""
    update_song_normal_form = "Update and add shows to the songs you picked out"
    update_song_back_to_menu_form = "Update and add shows to the songs you picked out --> Back to Menu"
    update_song_back_to_other_menu = "Update and add shows to the songs you picked out --> Link to other menu"
    update_song_back_to_other_form = "Update and add shows to the songs you picked out --> Link to other form"
    update_shows_multi_form = "Update child shows you picked out"
    update_show_normal_form = "Update Show"
    does_nothing_form = "This form does nothing"
